name: command_runner
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.3

# Add regular dependencies here.
dependencies:
   command_runner:
    path: ../command_runner # Points to your local command_runner package
    

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
